services:
  web:
    build: .
    container_name: calorifit_web
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/flaskdb
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: calorifit_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: flaskdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
